name: Actions Workflow
on: push

jobs:
  run-github-actions:
    runs-on: unbuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-actions@v1
        with:
          who-to-greet: Jim DevSecOps Master
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
